# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af69c39446d44acb82da3d57ea1e3cd9a570bb548f8a91a817f6b69f9a9cd2a3681fee1ee9a54a680846be2317ff7afdaf428b4932d6023d14483005602c5ed

test:
  secret_key_base: 0fbbdcbb6ed52eb39dbbce537ea9eb5523530a92d87d877e0608708ffe7b6419f29417b5322ca197e0cd96ea1c7e97bffd9290bd2fe16f343602b0cbac00603a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
